from PySpice.Spice.Netlist import Circuit
from PySpice.Unit import *
import matplotlib.pyplot as plt
import numpy as np

# Create the Two-Stage CMOS Op-Amp circuit
circuit = Circuit('Two-Stage CMOS Operational Amplifier')

# Supply voltages
VDD = 5  # Positive supply voltage
VSS = 0  # Negative supply (ground)
VBIAS = 2.5  # Bias voltage

# Define power supplies
circuit.V('dd', 'vdd', circuit.gnd, VDD@u_V)
circuit.V('ss', 'vss', circuit.gnd, VSS@u_V)

# Bias circuit
# RBIAS creates bias voltage for current mirror M8
circuit.R('BIAS', 'vdd', 'vbias', 100@u_kOhm)
circuit.V('bias', 'vbias', circuit.gnd, VBIAS@u_V)

# Input signal (differential input)
# For AC analysis, we'll use a small signal on vIN
# Using DC + AC specification
circuit.V('in_p', 'vin_p', circuit.gnd, '2.5 AC 0.5')  # Positive input with AC signal
circuit.V('in_n', 'vin_n', circuit.gnd, '2.5 AC 0')    # Negative input (reference)

# Current source loads (can be implemented with voltage sources for simplicity)
# In real design, these would be generated by current mirrors
circuit.I('DD', 'vdd', 'n_idd', 100@u_uA)  # Current source from VDD
circuit.I('SS', 'n_iss', circuit.gnd, 100@u_uA)  # Current sink to ground

# PMOS Current Mirror (M8, M1, M6)
# M8: Reference transistor for current mirror
circuit.MOSFET('M8', 'n_idd', 'vbias', 'vdd', 'vdd', model='PMOS')

# M1: Current source for differential pair
circuit.MOSFET('M1', 'n1', 'vbias', 'vdd', 'vdd', model='PMOS')

# M6: Current source for output stage
circuit.MOSFET('M6', 'n6', 'vbias', 'vdd', 'vdd', model='PMOS')

# Differential Input Pair (M2, M3) - NMOS
circuit.MOSFET('M2', 'n2', 'vin_p', 'n1', circuit.gnd, model='NMOS')
circuit.MOSFET('M3', 'n3', 'vin_n', 'n1', circuit.gnd, model='NMOS')

# Active Load Current Mirror (M4, M5) - PMOS
# M4: Reference for current mirror (diode-connected)
circuit.MOSFET('M4', 'n2', 'n2', 'vdd', 'vdd', model='PMOS')

# M5: Mirror load
circuit.MOSFET('M5', 'n3', 'n2', 'vdd', 'vdd', model='PMOS')

# Output Stage (M7) - NMOS common-source amplifier
circuit.MOSFET('M7', 'vout', 'n3', 'n_iss', circuit.gnd, model='NMOS')

# Compensation Capacitor (Miller compensation)
# CA (or CC) between gate of M7 and output
circuit.C('A', 'n3', 'vout', 2@u_pF)

# Additional compensation capacitor CB
circuit.C('B', 'vout', circuit.gnd, 1@u_pF)

# Load Capacitor
circuit.C('L', 'vout', circuit.gnd, 10@u_pF)

# Define NMOS model parameters
circuit.model('NMOS', 'nmos',
    level=1,
    kp=120e-6,      # Transconductance parameter
    vto=0.7,        # Threshold voltage
    lambda_=0.02,   # Channel length modulation
    gamma=0.37,     # Body effect parameter
    phi=0.65,       # Surface potential
    w=20e-6,        # Channel width (larger for input pair)
    l=1e-6          # Channel length
)

# Define PMOS model parameters
circuit.model('PMOS', 'pmos',
    level=1,
    kp=60e-6,       # Transconductance parameter (lower than NMOS)
    vto=-0.7,       # Threshold voltage (negative for PMOS)
    lambda_=0.02,   # Channel length modulation
    gamma=0.37,     # Body effect parameter
    phi=0.65,       # Surface potential
    w=40e-6,        # Channel width (2x NMOS to compensate mobility)
    l=1e-6          # Channel length
)

print("="*60)
print("TWO-STAGE CMOS OPERATIONAL AMPLIFIER")
print("="*60)
print(circuit)
print("="*60)

# Create simulator
simulator = circuit.simulator(temperature=25, nominal_temperature=25)

# Add simulation options for better convergence
simulator.options(reltol=1e-4, abstol=1e-9, vntol=1e-6)

try:
    print("\n1. Running DC Operating Point Analysis...")
    print("-"*60)

    # DC Operating Point Analysis
    dc_analysis = simulator.operating_point()

    print("DC Operating Point Results:")
    print(f"  Output voltage (vout): {float(dc_analysis['vout']):.3f} V")
    print(f"  Node n1 (diff pair source): {float(dc_analysis['n1']):.3f} V")
    print(f"  Node n2 (M2 drain): {float(dc_analysis['n2']):.3f} V")
    print(f"  Node n3 (M7 gate): {float(dc_analysis['n3']):.3f} V")

    print("\n2. Running AC Analysis (Frequency Response)...")
    print("-"*60)

    # AC Analysis for frequency response (Bode plot)
    # Input sources already have AC components defined
    ac_analysis = simulator.ac(
        start_frequency=1@u_Hz,
        stop_frequency=100@u_MHz,
        number_of_points=100,
        variation='dec'
    )

    # Calculate gain in dB and phase
    frequency = np.array(ac_analysis.frequency)
    vout_complex = np.array(ac_analysis['vout'])
    gain_db = 20 * np.log10(np.abs(vout_complex))
    phase_deg = np.angle(vout_complex, deg=True)

    # Find DC gain and unity-gain frequency
    dc_gain = gain_db[0]
    unity_gain_idx = np.where(gain_db <= 0)[0]
    if len(unity_gain_idx) > 0:
        unity_gain_freq = frequency[unity_gain_idx[0]]
        phase_margin = 180 + phase_deg[unity_gain_idx[0]]
        print(f"DC Gain: {dc_gain:.1f} dB")
        print(f"Unity-Gain Frequency: {unity_gain_freq/1e6:.2f} MHz")
        print(f"Phase Margin: {phase_margin:.1f} degrees")
    else:
        print(f"DC Gain: {dc_gain:.1f} dB")
        print("Unity-gain frequency not reached in simulation range")

    # Create Bode plot
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))

    # Magnitude plot
    ax1.semilogx(frequency, gain_db, 'b-', linewidth=2)
    ax1.grid(True, which='both', alpha=0.3)
    ax1.set_ylabel('Gain (dB)', fontsize=11)
    ax1.set_title('Two-Stage CMOS Op-Amp Frequency Response (Bode Plot)', fontsize=12, fontweight='bold')
    ax1.axhline(y=0, color='r', linestyle='--', alpha=0.5)

    # Phase plot
    ax2.semilogx(frequency, phase_deg, 'r-', linewidth=2)
    ax2.grid(True, which='both', alpha=0.3)
    ax2.set_xlabel('Frequency (Hz)', fontsize=11)
    ax2.set_ylabel('Phase (degrees)', fontsize=11)
    ax2.axhline(y=-180, color='r', linestyle='--', alpha=0.5)
    ax2.axhline(y=0, color='k', linestyle='-', alpha=0.3)

    plt.tight_layout()
    plt.savefig('opamp_bode_plot.png', dpi=300, bbox_inches='tight')
    print("\nBode plot saved as: opamp_bode_plot.png")
    plt.show()

    print("\n" + "="*60)
    print("Simulation completed successfully!")
    print("="*60)

except Exception as e:
    print(f"\nSimulation error: {str(e)}")
    print("Try adjusting transistor sizes or bias conditions.")
    import traceback
    traceback.print_exc()
